# Generated by Django 4.2 on 2023-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.TextField()),
                ('materi', models.TextField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
