# Generated by Django 4.2 on 2023-04-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assigments_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('deadline', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tugas',
        ),
        migrations.AddField(
            model_name='materi',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigments_model.matkul'),
        ),
        migrations.AddField(
            model_name='activity',
            name='materi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assigments_model.materi'),
        ),
    ]
