# Generated by Django 4.2 on 2023-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments_model', '0002_activity_materi_matkul_delete_tugas_materi_matkul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='open_time',
            field=models.DateTimeField(null=True),
        ),
    ]
