# Generated by Django 4.2 on 2023-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments_model', '0003_activity_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='id_num',
            field=models.TextField(null=True),
        ),
    ]
